{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "stroem.fullname" . }}
  labels:
    {{- include "stroem.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["create", "get", "list", "watch", "delete"]
{{- end }}
