apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stroem.fullname" . }}
  labels:
    {{- include "stroem.labels" . | nindent 4 }}
type: Opaque
data:
  worker-token: {{ .Values.workerToken | b64enc | quote }}
  database-url: {{ .Values.database.url | b64enc | quote }}
