{{- if .Values.server.logStorage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stroem.fullname" . }}-server-logs
  labels:
    {{- include "stroem.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
    {{- toYaml .Values.server.logStorage.persistence.accessModes | nindent 4 }}
  {{- with .Values.server.logStorage.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.logStorage.persistence.size }}
{{- end }}
