{{- if .Values.server.extraSecretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stroem.fullname" . }}-server-env
  labels:
    {{- include "stroem.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $value := .Values.server.extraSecretEnv }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
