{{- if .Values.worker.workspaceCache.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stroem.fullname" . }}-worker-cache
  labels:
    {{- include "stroem.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  accessModes:
    {{- toYaml .Values.worker.workspaceCache.persistence.accessModes | nindent 4 }}
  {{- with .Values.worker.workspaceCache.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.worker.workspaceCache.persistence.size }}
{{- end }}
